VIEW_RANK_TEST_INDEX = {
    "id": 1,
    "test_dataset": 1,
    "training_dataset": 2,
    "environment": 3,
    "distance": 4,
    "device": 5,
    "training_model": 6,
    "keybyte": 7,
    "epoch": 8,
    "additive_noise_method": 9,
    "additive_param_1": 10,
    "additive_param_1_value": 11,
    "additive_param_2": 12,
    "additive_param_2_value": 13,
    "denoising_method": 14,
    "denoising_param_1": 15,
    "denoising_param_1_value": 16,
    "denoising_param_2": 17,
    "denoising_param_2_value": 18,
    "termination_point": 19,
    "trace_process_id": 20,
    "date_added": 21,
}
